# Site settings
baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Paris Tango"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Paris Tango"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = ["css/paris-tango-stylesheet.css"]
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Paris"
    subtitle = "Tango"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About us"
      url = "about-us"

    [[params.navigation.links]]
      name = "Events"
      url = "events"

    # [[params.navigation.links]]
    #   name = "Generic Blog"
    #   url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Galleries"
      url = "galleries"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # # Button Style 1
    # [[params.navigation.button1]]
    #   name = "Get Started"
    #   url = "blogs"

    # # Button Style 2
    # [[params.navigation.button2]]
    #   name = "Log In"
    #   url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome to Paris Tango"
    subtitle = "We organise Argentine tango events, festivals, classes and workshops in the UK and tango holidays in France"
    buttonText = "Events"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "History"
      subtitle = "About Brigitte"
      image = "Bs2019_Brigittepix1_2008.jpeg"
      url = "about-us"

    [[params.tiles.showcase]]
      title = "Events"
      subtitle = "Our upcoming and past events"
      image = "F&F-2010 portraits  201.jpg"
      url = "events"

    [[params.tiles.showcase]]
      title = "Photo Gallery: Championships"
      subtitle = "Tango championships and festivals"
      image = "F&F-2010 dancers  212.jpg"
      url = "galleries/tango-championships"

    [[params.tiles.showcase]]
      title = "Photo Gallery: Brigitte"
      subtitle = "Brigitte and her partners"
      image = "Bs2019_Brigittepix2_2008.jpeg"
      url = "galleries/brigitte-and-partners"

    [[params.tiles.showcase]]
      title = "Photo Gallery: Friends"
      subtitle = "Some of my dearest tango friends"
      image = "CIMG9211.jpeg"
      url = "galleries/ricardo-vido"

    [[params.tiles.showcase]]
      title = "Photo Gallery: Tango Holidays"
      subtitle = "Holidays organised by Paris Tango: Paris, Chateau Juvenal, Avignon"
      image = "Bs2019_3ParisMilonga2007.jpeg"
      url = "galleries/tango-holidays"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Paris Tango"
    subtitle = """Tango with Brigitte is based in London, UK. Best known for the sumptuous Fire & Flame Ball in London and Chateau tango holidays in France.

We organise Argentine tango events, festivals, classes and workshops in the UK, and tango holidays in France.

We represent in the UK carefully selected Argentine tango teachers and musicians. We host many internationally renowned dancers and musicians.

We offer private tuition for beginners and all levels of dance at our venue in South Hampstead.

Private parties and functions: Performances, introduction to tango, first steps and demonstrations.

Weddings: Learn to dance for your big day and open the ball in style.

We will help you find the most suitable classes and teachers to suit your needs.

If you are a visitor we will inform you where to dance in the UK and in France during your visit. We can also help you find suitable accommodation."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send / Envoi"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.instructions]]
    title = ""
    instructions = ""

    [[params.contact.email]]
    title = "Email"
    email = "brigitte@paris-tango.co.uk"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 (0) 7818 808 711"

    # [[params.contact.address]]
    # title = "Address"
    # street = "Street"
    # city = "City, ST 00000"
    # country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Paris Tango"

    # Paris Tango doesn't use Twitter, remove from footer
    # to re-activate, remove all comments from following lines
    # and insert the correct Twitter URL
    #
    # Uses font awesome icons
    # [[params.footer.social]]
    #   icon = "fa-twitter"
    #   url= "https://www.twitter.com"
    #   label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/Tango-with-Brigitte-Paris-Tango-132599513425720/"
      label = "Facebook"

    # Paris Tango doesn't use Instagram or LinkedIn, remove from footer
    # to re-activate, remove all comments from following lines
    # and insert the correct Instagram or LinkedIn URLs

    # [[params.footer.social]]
    #   icon = "fa-instagram"
    #   url= "https://www.instagram.com"
    #   label = "Instagram"
    
    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   url= "https://www.linkedin.com"
    #   label = "LinkedIn"

    # [[params.footer.quicklinks]]
    #   text = "Design: "
    #   url= "https://www.html5up.net"
    #   alt = "HTML5 UP"
