# Site settings
baseURL = "https://paris-tango.co.uk/"
languageCode = "en-gb"
title = "Paris Tango"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Paris Tango"
  description = "We organise Argentine tango events, festivals, classes and workshops in the UK and tango holidays in France"

  # Link custom assets relative to /static
  custom_css = ["css/paris-tango-stylesheet.css"]
  custom_js  = []
  favicon    = "favicon.ico"


  mediaSecureDeliveryURL = "https://res.cloudinary.com/paris-tango/"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Paris"
    subtitle = "Tango"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About us"
      url = "about-us"

    [[params.navigation.links]]
      name = "Events"
      url = "events"

    # [[params.navigation.links]]
    #   name = "Generic Blog"
    #   url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Galleries"
      url = "galleries"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # # Button Style 1
    # [[params.navigation.button1]]
    #   name = "Get Started"
    #   url = "blogs"

    # # Button Style 2
    # [[params.navigation.button2]]
    #   name = "Log In"
    #   url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome to Paris Tango"
    subtitle = "We organise Argentine tango events, festivals, classes and workshops in the UK and tango holidays in France"
    buttonText = "Events"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here in even pairs as the layout
    # is designed to display two tiles side-by-side
    
    # The first tile section is for the display of featured pages
    [[params.tiles.featuredPage]]
      title = "History"
      subtitle = "About Brigitte"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552521473/Brigitte_Martin-_original-_2008.jpg"
      url = "about-us"

    [[params.tiles.featuredPage]]
      title = "Events"
      subtitle = "Our upcoming and past events"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552521474/F_F-2010_portraits_201.jpg"
      url = "events"


    # The second tile section is for the display of photo galleries
    [params.tiles.photoGallerySection]
    enableSection = true        # enable the photo gallery section
    enableSeparatorSection = true # enable a separator with a title and subtitle

    title = "Photo Galleries"
    subtitle = """Browse through photo galleries of our past events, festivals and championships; see with whom we've worked over the years, our tango friends and holidays."""

    [[params.tiles.photoGallery]]
      title = "Events and Festivals"
      subtitle = "Events, festivals and championships"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552521474/F_F-2010_dancers_212.jpg"
      url = "galleries/events-festivals-and-tango-championships"

    [[params.tiles.photoGallery]]
      title = "Agency"
      subtitle = "Brigitte and her clients"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552525987/Bs2019_Brigittepix2_2008.jpg"
      url = "galleries/agency"

    [[params.tiles.photoGallery]]
      title = "Friends"
      subtitle = "Some of my dearest tango friends"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552445820/CIMG9211.jpg"
      url = "galleries/tango-friends"

    [[params.tiles.photoGallery]]
      title = "Tango Holidays"
      subtitle = "Holidays organised by Paris Tango: Paris, Chateau Juvenal, Avignon"
      image = "https://res.cloudinary.com/paris-tango/image/upload/v1552523653/Bs2019_3ParisMilonga2007.jpg"
      url = "galleries/tango-holidays"
    # You can make more showcases by copy and pasting the code above, in pairs

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Paris Tango"
    subtitle = """Tango with Brigitte is based in London, UK. Best known for the sumptuous Fire & Flame Ball in London and Chateau tango holidays in France, we organise Argentine tango events, festivals, classes and workshops in the UK, and tango holidays in France.

We represent internationally renowned artists and host in the UK carefully selected Argentine tango teachers and musicians.

We offer private tuition for beginners and all levels of dance at our venue in South Hampstead. We will help you find the most suitable classes and teachers to suit your needs.

Private parties and functions: Performances, introduction to tango, first steps and demonstrations.

Weddings: Learn to dance for your big day and open the ball in style.

If you are a visitor we will inform you where to dance in the UK and in France during your visit. We can also help you find suitable accommodation."""
    buttonText = "About us"
    url = "about-us"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send / Envoi"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "brigitte@paris-tango.co.uk"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.instructions]]
    title = ""
    instructions = ""

    [[params.contact.email]]
    title = "Email"
    email = "brigitte@paris-tango.co.uk"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 (0) 7818 808 711"

    # [[params.contact.address]]
    # title = "Address"
    # street = "Street"
    # city = "City, ST 00000"
    # country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Paris Tango"

    # Paris Tango doesn't use Twitter, remove from footer
    # to re-activate, remove all comments from following lines
    # and insert the correct Twitter URL
    #
    # Uses font awesome icons
    # [[params.footer.social]]
    #   icon = "fa-twitter"
    #   url= "https://www.twitter.com"
    #   label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/Tango-with-Brigitte-Paris-Tango-132599513425720/"
      label = "Facebook page"

    # Paris Tango doesn't use Instagram or LinkedIn, remove from footer
    # to re-activate, remove all comments from following lines
    # and insert the correct Instagram or LinkedIn URLs

    # [[params.footer.social]]
    #   icon = "fa-instagram"
    #   url= "https://www.instagram.com"
    #   label = "Instagram"
    
    # [[params.footer.social]]
    #   icon = "fa-linkedin"
    #   url= "https://www.linkedin.com"
    #   label = "LinkedIn"

    # [[params.footer.quicklinks]]
    #   text = "Design: "
    #   url= "https://www.html5up.net"
    #   alt = "HTML5 UP"
